defaults:
  - backbone: wgan-gp-in
  - _self_

name: wgan
channels: 3
generator_iters: 40000 # 40000 default
lambda_term: 1e-4
number_of_images: 100
use_checkpoint: false

training:
  epochs: 50
  batch_size: 128
  device: cuda
  save_flag: false

evaluation:
  eval_interval: 200
  number_of_generated_images_for_inception_score_calculation: 8000
  save_img: true
  use_is: true
  use_fid: true