defaults:
  - _self_
  - optimizers: adam
  - datasets: cifar10
  - models: wgan


setup:
  torch:
    seed: 8
  random:
    seed: 8
  numpy:
    seed: 8

training:
  epochs: 200
  save_interval: 10
  sample_interval: 100
  checkpoint: null
  device: cuda
  log_interval: 100