defaults:
  - _self_
  - optimizers: adafm
  - datasets: cifar10
  - models: wgan


setup:
  torch:
    seed: 8
  random:
    seed: 8
  numpy:
    seed: 8
  device: cuda

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    level: INFO
  output_subdir: null