defaults:
  - _self_
  - optimizers: adam
  - datasets: cifar10
  - models: wgan

result_folder: results/

experiment_type: g_l_observation # g_l_observation | delta_test | default | gp_exp | loss_lr

setup:
  seed: 8
  torch:
    seed: 8
  random:
    seed: 8
  numpy:
    seed: 8
  device: cuda:0

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job_logging:
    level: INFO
  output_subdir: null

tensorboard:
  log_dir_root: ./tensorboard_logs